---
- name: Check host status
  hosts: templates
  become: true
  become_method: sudo
  gather_facts: False

  tasks:
  - name: add host to group 'stage'
    add_host:
      name: "{{ ansible_host  }}"
      groups: stage
    vars:
      remote_user: deploy

  - name: Generate stage hosts file
    include: ../tasks/hosts_stage.yml
    delegate_to: localhost
