---
  - name: Check logon success.
    ignore_errors: True
    changed_when: no
    failed_when: no
    any_errors_fatal: False
    wait_for_connection:
      delay: 5
      sleep: 1
      timeout: 60 
    register: task_check_user
